services:
  - type: web
    name: snapurl-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install uv && uv sync --frozen --no-dev && uv run alembic upgrade head
    startCommand: uv run uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: DEBUG
        value: false
      - key: TESTING
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: snapurl-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: '["http://localhost:5173","https://snapurl-fdkn3kn04-muhammad-sulemans-projects-494c53f6.vercel.app"]'
      - key: ALLOWED_ORIGIN_REGEX
        value: '^https://.*\\.vercel\\.app$'
      - key: BASE_URL
        value: https://snapurl-app-1tl5.onrender.com

databases:
  - name: snapurl-db
    plan: free
